name: 'CloudWatch Logs Actions'
description: 'GitHub action that integrates with Amazon CloudWatch Logs'
author: 'MooYeol Prescott Lee'
inputs:
  # Common
  region:
    description: 'AWS Region'
    required: false
  group:
    description: 'Log Group Name'
    required: true
  stream:
    description: 'Log Stream Name'
    required: true
  run:
    description: 'Command to run'
    required: true
  shell:
    description: 'Override shell'
    required: false
  retention:
    description: 'The number of days to retain the log events in the specified log group.'
    required: false
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'activity'
  color: 'green'
